### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by gagan-bansal** [normanb/nodesidx#2]
First of all its great work.
I might be doing some silly mistake while building.
I am not able to build, here is the log:
```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.3.1 | linux | x64
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/gaganb/rev-geocode/nodesidx/build'
  CXX(target) Release/obj.target/libspatialindex/deps/libspatialindex/src/tools/rand48.o
In file included from ../deps/libspatialindex/src/tools/rand48.cc:18:0:
../deps/libspatialindex/include/spatialindex/tools/rand48.h:60:0: warning: "__THROW" redefined [enabled by default]
 #   define __THROW
 ^
In file included from /usr/include/features.h:375:0,
                 from /usr/include/math.h:27,
                 from ../deps/libspatialindex/src/tools/rand48.cc:16:
/usr/include/sys/cdefs.h:61:0: note: this is the location of the previous definition
 #   define __THROW throw ()
 ^
In file included from ../deps/libspatialindex/src/tools/rand48.cc:18:0:
../deps/libspatialindex/include/spatialindex/tools/rand48.h:61:0: warning: "__NTH" redefined [enabled by default]
 #   define __NTH(fct)  fct
 ^
In file included from /usr/include/features.h:375:0,
                 from /usr/include/math.h:27,
                 from ../deps/libspatialindex/src/tools/rand48.cc:16:
/usr/include/sys/cdefs.h:63:0: note: this is the location of the previous definition
 #   define __NTH(fct) __LEAF_ATTR fct throw ()
 ^
../deps/libspatialindex/src/tools/rand48.cc: In function ‘short unsigned int* seed48(short unsigned int*)’:
../deps/libspatialindex/src/tools/rand48.cc:80:31: error: declaration of ‘short unsigned int* seed48(short unsigned int*)’ has a different exception specifier
 seed48(unsigned short xseed[3]) __THROW
                               ^
In file included from ../deps/libspatialindex/src/tools/rand48.cc:18:0:
../deps/libspatialindex/include/spatialindex/tools/rand48.h:66:24: error: from previous declaration ‘short unsigned int* seed48(short unsigned int*) throw ()’
 extern unsigned short *seed48(unsigned short xseed[3]) __THROW;
                        ^
../deps/libspatialindex/src/tools/rand48.cc: In function ‘long int nrand48(short unsigned int*)’:
../deps/libspatialindex/src/tools/rand48.cc:98:32: error: declaration of ‘long int nrand48(short unsigned int*)’ has a different exception specifier
 nrand48(unsigned short xseed[3]) __THROW
                                ^
In file included from ../deps/libspatialindex/src/tools/rand48.cc:18:0:
../deps/libspatialindex/include/spatialindex/tools/rand48.h:68:13: error: from previous declaration ‘long int nrand48(short unsigned int*) throw ()’
 extern long nrand48(unsigned short xseed[3]) __THROW;
             ^
../deps/libspatialindex/src/tools/rand48.cc:118:28: error: declaration of ‘void lcong48(short unsigned int*)’ has a different exception specifier
 lcong48(unsigned short p[7]) __THROW
                            ^
In file included from ../deps/libspatialindex/src/tools/rand48.cc:18:0:
../deps/libspatialindex/include/spatialindex/tools/rand48.h:74:13: error: from previous declaration ‘void lcong48(short unsigned int*) throw ()’
 extern void lcong48(unsigned short p[7]) __THROW;
             ^
../deps/libspatialindex/src/tools/rand48.cc: In function ‘long int jrand48(short unsigned int*)’:
../deps/libspatialindex/src/tools/rand48.cc:129:32: error: declaration of ‘long int jrand48(short unsigned int*)’ has a different exception specifier
 jrand48(unsigned short xseed[3]) __THROW
                                ^
In file included from ../deps/libspatialindex/src/tools/rand48.cc:18:0:
../deps/libspatialindex/include/spatialindex/tools/rand48.h:76:13: error: from previous declaration ‘long int jrand48(short unsigned int*) throw ()’
 extern long jrand48(unsigned short xseed[3]) __THROW;
             ^
../deps/libspatialindex/src/tools/rand48.cc: In function ‘double erand48(short unsigned int*)’:
../deps/libspatialindex/src/tools/rand48.cc:136:32: error: declaration of ‘double erand48(short unsigned int*)’ has a different exception specifier
 erand48(unsigned short xseed[3]) __THROW
                                ^
In file included from ../deps/libspatialindex/src/tools/rand48.cc:18:0:
../deps/libspatialindex/include/spatialindex/tools/rand48.h:78:15: error: from previous declaration ‘double erand48(short unsigned int*) throw ()’
 extern double erand48(unsigned short xseed[3]) __THROW;
ake: *** [Release/obj.target/libspatialindex/deps/libspatialindex/src/tools/rand48.o] Error 1
make: Leaving directory `/home/gaganb/rev-geocode/nodesidx/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/gaganb/rev-geocode/nodesidx/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.10.0-123.el7.x86_64
gyp ERR! command "/home/gaganb/.nvm/versions/node/v6.3.1/bin/node" "/home/gaganb/rev-geocode/nodesidx/node_modules/.bin/node-gyp" "build"
gyp ERR! cwd /home/gaganb/rev-geocode/nodesidx
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

```

**Comment by normanb** [comment]
I can see you are using linux, I can use an image and try and recreate this. What version are you running?

**Comment by gagan-bansal** [comment]
I tried on CentOS 7 and Ubuntu 16.04, error is same. 
So you can try on any Linux dist.
